name: noodle_text
description: Simple alternative to RichText
version: 1.0.1
homepage: https://github.com/Noodle-Cx/noodle_packages/noodle_text

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: