name: noodle_camera
description: Complete Widget to use camera to take pictures or Scan codes.
version: 1.0.0
homepage: https://github.com/Noodle-Cx/noodle_camera

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.0
  flutter:
    sdk: flutter
  google_ml_kit: ^0.11.0
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

