name: noodle_utils
description: Noodle Utils
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  decimal: ^1.3.0
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.3
  stark: ^3.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
